### ISSUE TITLE
Error interrupted conversion

### ISSUE THREAD

**Issue by zakgreene** [qqilihq/partial-emlx-converter#3] opened 2019-03-05 22:37 UTC
When I ran the script, it converted exactly 10 messages, and then I got this error, which unfortunately terminated the process.

```
(node:84936) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '../archive.mbox/8C963429-A03A-442E-BFCA-76C71193F741/Data/0/1/Attachments/10010/2.2/map_6e1b1a73-4f66-484b-bad9-56004041cc80'
```

It'd be great if there were a way to just skip attachments it can't find. I'm trying to recover messages from a Time Machine backup. I'd be perfectly content if it just left out all attachments.

**Comment by qqilihq** [comment] 2019-03-05 23:06
Understand your point. Unfortunately I don't have much spare time at the moment. 

Would you be able and willing to contribute a PR?

**Comment by zakgreene** [comment] 2019-03-06 01:02
I would, except I'm not too familiar with Node. Sorry.

**Comment by qqilihq** [comment] 2019-03-06 13:15
@zakgreene Skipped lunch and did this instead. Can you give it a try and give feedback?

**Comment by zakgreene** [comment] 2019-03-08 17:48
That seemed to work well, thanks! I encountered another error, below, which interrupted the conversion but I think is unrelated to missing attachments. I can't quite tell what the issue is. It converted 587 messages (of several thousand).

```
(node:19703) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at transformRec (/Users/zak/Desktop/email/partial-emlx-converter-master/build/src/converter.js:112:31)
    at part.part.body.forEach (/Users/zak/Desktop/email/partial-emlx-converter-master/build/src/converter.js:106:49)
    at Array.forEach (<anonymous>)
    at transformRec (/Users/zak/Desktop/email/partial-emlx-converter-master/build/src/converter.js:106:24)
    at parts.forEach (/Users/zak/Desktop/email/partial-emlx-converter-master/build/src/converter.js:98:36)
    at Array.forEach (<anonymous>)
    at transform (/Users/zak/Desktop/email/partial-emlx-converter-master/build/src/converter.js:98:11)
    at emlformat.parse (/Users/zak/Desktop/email/partial-emlx-converter-master/build/src/converter.js:49:17)
(node:19703) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

I was able to find a different way to restore my messages (I still had access to my old server) and didn't need to use the Time Machine backup from the `~/Library/Mail` folder after all. Those messages seem to be stored in a complex web of folders, so it may be a difficult use case to support. But happy to help more if it's something you'd like to fix. Thanks for your work.

**Comment by qqilihq** [comment] 2019-03-08 18:09
That's interesting -- obviously, the attachment filename cannot be extracted from the email.

I'll see whether I can reproduce this locally with a bigger email archive. Maybe I'll get back to you in case I'd need additional input -- thanks so far!

**Comment by qqilihq** [comment] 2019-03-10 10:35
Thanks again. The reason was, that the script did not correctly handle attachments which did not provide a filename in the `Content-Disposition` or `Content-Type` header.

This is fixed now.

**Closed by qqilihq** 2019-03-10 10:35 UTC
